// STM32F0 serial
//
// Copyright (C) 2019  Kevin O'Connor <kevin@koconnor.net>
//
// This file may be distributed under the terms of the GNU GPLv3 license.

#include "autoconf.h" // CONFIG_SERIAL_BAUD
#include "board/armcm_boot.h" // armcm_enable_irq
#include "board/serial_irq.h" // serial_rx_byte
#include "command.h" // DECL_CONSTANT_STR
#include "internal.h" // enable_pclock
#include "sched.h" // DECL_INIT

#if CONFIG_STM32_SERIAL_RS485
#include "ctr.h" // DECL_CTR
DECL_CTR("DECL_SERIAL_DE_PIN " __stringify(CONFIG_STM32_SERIAL_DE_PIN));
extern uint32_t serial_de_gpio; // Generated by buildcommands.py

// Build-time validation for the H723 hardware DE alternate-function pins.
// Other H7 variants retain the typed-pin interface without assuming that
// their pin maps are identical to the H723.
#if CONFIG_MACH_STM32H723
  #if CONFIG_STM32_SERIAL_USART1 || CONFIG_STM32_SERIAL_USART1_ALT_PB7_PB6
    DECL_CONSTANT_STR("SERIAL_DE_PINS", "PA12");
  #elif CONFIG_STM32_SERIAL_USART2 || CONFIG_STM32_SERIAL_USART2_ALT_PD6_PD5
    DECL_CONSTANT_STR("SERIAL_DE_PINS", "PA1,PD4");
  #elif CONFIG_STM32_SERIAL_USART3 || CONFIG_STM32_SERIAL_USART3_ALT_PD9_PD8
    DECL_CONSTANT_STR("SERIAL_DE_PINS", "PB14,PD12");
  #elif CONFIG_STM32_SERIAL_UART4
    DECL_CONSTANT_STR("SERIAL_DE_PINS", "PA15,PB14");
  #endif
#endif
#endif

// Select the configured serial port
#if CONFIG_STM32_SERIAL_USART1
  DECL_CONSTANT_STR("RESERVE_PINS_serial", "PA10,PA9");
  #define GPIO_Rx GPIO('A', 10)
  #define GPIO_Tx GPIO('A', 9)
  #define USARTx_FUNCTION GPIO_FUNCTION( \
            (CONFIG_MACH_STM32H7 | CONFIG_MACH_STM32G4) ? 7 : 1)
  #define USARTx USART1
  #define USARTx_IRQn USART1_IRQn
#elif CONFIG_STM32_SERIAL_USART1_ALT_PB7_PB6
  DECL_CONSTANT_STR("RESERVE_PINS_serial", "PB7,PB6");
  #define GPIO_Rx GPIO('B', 7)
  #define GPIO_Tx GPIO('B', 6)
  #define USARTx_FUNCTION GPIO_FUNCTION( \
            (CONFIG_MACH_STM32H7 | CONFIG_MACH_STM32G4) ? 7 : 0)
  #define USARTx USART1
  #define USARTx_IRQn USART1_IRQn
#elif CONFIG_STM32_SERIAL_USART2
  DECL_CONSTANT_STR("RESERVE_PINS_serial", "PA3,PA2");
  #define GPIO_Rx GPIO('A', 3)
  #define GPIO_Tx GPIO('A', 2)
  #define USARTx_FUNCTION GPIO_FUNCTION( \
            (CONFIG_MACH_STM32H7 | CONFIG_MACH_STM32G4) ? 7 : 1)
  #define USARTx USART2
  #define USARTx_IRQn USART2_IRQn
#elif CONFIG_STM32_SERIAL_USART2_ALT_PA15_PA14
  DECL_CONSTANT_STR("RESERVE_PINS_serial", "PA15,PA14");
  #define GPIO_Rx GPIO('A', 15)
  #define GPIO_Tx GPIO('A', 14)
  #define USARTx_FUNCTION GPIO_FUNCTION(CONFIG_MACH_STM32G4 ? 7 : 1)
  #define USARTx USART2
  #define USARTx_IRQn USART2_IRQn
#elif CONFIG_STM32_SERIAL_USART2_ALT_PB4_PB3
  DECL_CONSTANT_STR("RESERVE_PINS_serial", "PB4,PB3");
  #define GPIO_Rx GPIO('B', 4)
  #define GPIO_Tx GPIO('B', 3)
  #define USARTx_FUNCTION GPIO_FUNCTION(7)
  #define USARTx USART2
  #define USARTx_IRQn USART2_IRQn
#elif CONFIG_STM32_SERIAL_USART2_ALT_PD6_PD5
  DECL_CONSTANT_STR("RESERVE_PINS_serial", "PD6,PD5");
  #define GPIO_Rx GPIO('D', 6)
  #define GPIO_Tx GPIO('D', 5)
  #define USARTx_FUNCTION GPIO_FUNCTION(7)
  #define USARTx USART2
  #define USARTx_IRQn USART2_IRQn
#elif CONFIG_STM32_SERIAL_USART3
  DECL_CONSTANT_STR("RESERVE_PINS_serial", "PB11,PB10");
  #define GPIO_Rx GPIO('B', 11)
  #define GPIO_Tx GPIO('B', 10)
  #define USARTx_FUNCTION GPIO_FUNCTION(7)
  #define USARTx USART3
  #define USARTx_IRQn USART3_IRQn
#elif CONFIG_STM32_SERIAL_USART3_ALT_PD9_PD8
  DECL_CONSTANT_STR("RESERVE_PINS_serial", "PD9,PD8");
  #define GPIO_Rx GPIO('D', 9)
  #define GPIO_Tx GPIO('D', 8)
  #define USARTx_FUNCTION GPIO_FUNCTION(CONFIG_MACH_STM32G0 ? 0 : 7)
  #define USARTx USART3
  #define USARTx_IRQn USART3_IRQn
#elif CONFIG_STM32_SERIAL_USART3_ALT_PC11_PC10
  //  Currently only supports STM32G474.
  DECL_CONSTANT_STR("RESERVE_PINS_serial", "PC11,PC10");
  #define GPIO_Rx GPIO('C', 11)
  #define GPIO_Tx GPIO('C', 10)
  #define USARTx_FUNCTION GPIO_FUNCTION(7)
  #define USARTx USART3
  #define USARTx_IRQn USART3_IRQn
#elif CONFIG_STM32_SERIAL_UART4
  DECL_CONSTANT_STR("RESERVE_PINS_serial", "PA1,PA0");
  #define GPIO_Rx GPIO('A', 1)
  #define GPIO_Tx GPIO('A', 0)
  #define USARTx_FUNCTION GPIO_FUNCTION(8)
  #define USARTx UART4
  #define USARTx_IRQn UART4_IRQn
#elif CONFIG_STM32_SERIAL_USART5
  DECL_CONSTANT_STR("RESERVE_PINS_serial", "PD2,PD3");
  #define GPIO_Rx GPIO('D', 2)
  #define GPIO_Tx GPIO('D', 3)
  #define USARTx_FUNCTION GPIO_FUNCTION(3)
  #define USARTx USART5
  #define USARTx_IRQn USART5_IRQn
#endif

#if CONFIG_MACH_STM32F031
  // The stm32f031 has same pins for USART2, but everything is routed to USART1
  #define USART2 USART1
  #define USART2_IRQn USART1_IRQn
#endif

#if CONFIG_MACH_STM32G0
  // Some of the stm32g0 MCUs have slightly different register names
  #if CONFIG_MACH_STM32G0B1
    #define USART2_IRQn USART2_LPUART2_IRQn
    #define USART3_IRQn USART3_4_5_6_LPUART1_IRQn
    #define USART4_IRQn USART3_4_5_6_LPUART1_IRQn
    #define USART5_IRQn USART3_4_5_6_LPUART1_IRQn
    #define USART6_IRQn USART3_4_5_6_LPUART1_IRQn
  #endif
  #if CONFIG_MACH_STM32G0B0
    #define USART2_IRQn USART2_IRQn
    #define USART3_IRQn USART3_4_5_6_IRQn
    #define USART4_IRQn USART3_4_5_6_IRQn
    #define USART5_IRQn USART3_4_5_6_IRQn
    #define USART6_IRQn USART3_4_5_6_IRQn
  #endif
  #define USART_CR1_RXNEIE USART_CR1_RXNEIE_RXFNEIE
  #define USART_CR1_TXEIE USART_CR1_TXEIE_TXFNFIE
  #define USART_ISR_RXNE USART_ISR_RXNE_RXFNE
  #define USART_ISR_TXE USART_ISR_TXE_TXFNF
  #define USART_BRR_DIV_MANTISSA_Pos 4
  #define USART_BRR_DIV_FRACTION_Pos 0
#elif CONFIG_MACH_STM32G4
  #define USART_BRR_DIV_MANTISSA_Pos 4
  #define USART_BRR_DIV_FRACTION_Pos 0
#elif CONFIG_MACH_STM32H7
  // The stm32h7 has slightly different register names
  #define USART_ISR_RXNE USART_ISR_RXNE_RXFNE
  #define USART_ISR_TXE USART_ISR_TXE_TXFNF
#endif

#define USE_SERIAL_DE CONFIG_STM32_SERIAL_RS485

#if CONFIG_STM32_SERIAL_RS485
// Driver-enable assertion/deassertion guard of half a bit time (8/16
// oversampling ticks).  DEAT/DEDT live in CR1 and are writable only while
// UE=0, so they are included in every CR1 state so no write clears them.
#define CR1_DE_TIMING ((8 << USART_CR1_DEAT_Pos) | (8 << USART_CR1_DEDT_Pos))
#else
#define CR1_DE_TIMING 0
#endif

#define CR1_FLAGS (USART_CR1_UE | USART_CR1_RE | USART_CR1_TE   \
                   | USART_CR1_RXNEIE | CR1_DE_TIMING)
#define CR1_TX_FLAGS (USART_CR1_UE | USART_CR1_TE | CR1_DE_TIMING)

static void
serial_start_tx(void)
{
    // Disable reception while the always-enabled transceiver receiver
    // observes our own transmission.
    USARTx->CR1 = CR1_TX_FLAGS | USART_CR1_TXEIE;
}

#if CONFIG_STM32_SERIAL_RS485
uint_fast8_t
serial_tx_is_active(void)
{
    return !(USARTx->CR1 & USART_CR1_RE);
}
#endif

void
USARTx_IRQHandler(void)
{
    uint32_t sr = USARTx->ISR;
    while ((sr & USART_ISR_RXNE) && (!USE_SERIAL_DE
                                     || (USARTx->CR1 & USART_CR1_RE))) {
        uint8_t data = USARTx->RDR;
        serial_rx_byte(data);
        sr = USARTx->ISR;
    }
    // A framing/noise error on a shared RS485 bus (e.g. during direction
    // turnaround) must not be allowed to linger; clear any error flags seen.
    if (sr & 0x0f)
        USARTx->ICR = sr & 0x0f; // PECF/FECF/NCF/ORECF share ISR positions
    if (sr & USART_ISR_TXE && USARTx->CR1 & USART_CR1_TXEIE) {
        uint8_t data;
        int ret = serial_get_tx_byte(&data);
        if (!ret) {
            USARTx->TDR = data;
        } else if (USE_SERIAL_DE) {
            // Keep hardware DE asserted through the final stop bit.
            USARTx->CR1 = CR1_TX_FLAGS | USART_CR1_TCIE;
        } else {
            USARTx->CR1 = CR1_FLAGS;
        }
    }
    if (USE_SERIAL_DE && (sr & USART_ISR_TC)
        && (USARTx->CR1 & USART_CR1_TCIE)) {
        USARTx->ICR = USART_ICR_TCCF;
        // A byte that completed just before reception was disabled at turn
        // start can still sit unread in RDR; it belongs to a dead exchange
        // and would otherwise be prepended to the next turn's input.
        USARTx->RQR = USART_RQR_RXFRQ;
        USARTx->CR1 = CR1_FLAGS;
    }
}

void
serial_enable_tx_irq(void)
{
    if (!USE_SERIAL_DE) {
        USARTx->CR1 = CR1_FLAGS | USART_CR1_TXEIE;
        return;
    }
    // Callers guarantee transmit data is queued before enabling (verified
    // under irq-off): enabling with an empty buffer would arm TCIE with no
    // completion ever coming, leaving reception disabled permanently.
    serial_start_tx();
}

void
serial_init(void)
{
    enable_pclock((uint32_t)USARTx);

#if CONFIG_STM32_SERIAL_RS485
    gpio_peripheral(serial_de_gpio, USARTx_FUNCTION, 0);
#endif

    uint32_t pclk = get_pclock_frequency((uint32_t)USARTx);
    uint32_t div = DIV_ROUND_CLOSEST(pclk, CONFIG_SERIAL_BAUD);
    USARTx->BRR = (((div / 16) << USART_BRR_DIV_MANTISSA_Pos)
                   | ((div % 16) << USART_BRR_DIV_FRACTION_Pos));
    USARTx->CR3 = USART_CR3_OVRDIS; // disable the ORE ISR
    if (USE_SERIAL_DE)
        // Active-high is the reset polarity; hardware controls DE.
        USARTx->CR3 |= USART_CR3_DEM;
    // DEAT/DEDT may only be programmed while UE is clear
    USARTx->CR1 = CR1_FLAGS & ~USART_CR1_UE;
    USARTx->CR1 = CR1_FLAGS;
    armcm_enable_irq(USARTx_IRQHandler, USARTx_IRQn, 0);

    gpio_peripheral(GPIO_Rx, USARTx_FUNCTION, 1);
    gpio_peripheral(GPIO_Tx, USARTx_FUNCTION, 0);
}
DECL_INIT(serial_init);
